// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDj28id8Ieg1gg7AlWUYxzdq50_ozKA4',
    appId: '1:487247110048:web:31ab7aa6e75f86a42c4ec5',
    messagingSenderId: '487247110048',
    projectId: 'gameglimpse-5e114',
    authDomain: 'gameglimpse-5e114.firebaseapp.com',
    storageBucket: 'gameglimpse-5e114.appspot.com',
    measurementId: 'G-RYJS605E5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkhT-nk-UpX47k101ysORd3T8vT6xmHI',
    appId: '1:487247110048:android:9d3fdb5f661b9ee72c4ec5',
    messagingSenderId: '487247110048',
    projectId: 'gameglimpse-5e114',
    storageBucket: 'gameglimpse-5e114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_OsrVgcgbeejUa7c4rfJ6db0KpaWG1g',
    appId: '1:487247110048:ios:b5a4ad103f503e322c4ec5',
    messagingSenderId: '487247110048',
    projectId: 'gameglimpse-5e114',
    storageBucket: 'gameglimpse-5e114.appspot.com',
    iosBundleId: 'com.example.gpApp',
  );
}
